# Generated by Django 2.2.6 on 2019-10-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
